version: '3.6'
services:
  registrator:
    image: gliderlabs/registrator:vendor
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    # setting `-internal=true` will cause linkerd and namerd to fail silently
    command: -ip=docker.for.mac.localhost -deregister=always -cleanup -tags=registrator consul://consul:8500
    networks:
      grpc:

  consul:
    image: consul:1.0.6
    restart: always
    ports:
      - 127.0.0.1:8500:8500
    networks:
      grpc:

  traefik:
    image: traefik:1.6
    restart: always
    ports:
      - 127.0.0.1:8080:8080 # UI
      - 127.0.0.1:80:80 # HTTP
      - 127.0.0.1:4443:4443 # HTTPS
    volumes:
      - $PWD/config/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - backend.cert
      - frontend.cert
      - frontend.key
    networks:
      grpc:
        aliases:
          - frontend.local

  server:
    image: alextanhongpin/grpc-server:latest
    ports:
      - 127.0.0.1::50051
    environment:
      - PORT=:50051
      - SSL_CERT=/run/secrets/backend.cert
      - SSL_KEY=/run/secrets/backend.key
    secrets:
      - backend.cert
      - backend.key
    # labels:
      # Enables the consul_catalog, by passing the tags to consul through registrator
      # - SERVICE_NAME=server
      # - SERVICE_REGION=ap-southeast-1
      ## NOTE: Not all configuration is available - see the Backend: Consul Catalog documentation
      # - SERVICE_TAGS=traefik.enable=true,traefik.frontend.entryPoint=https,traefik.frontend.rule=Host:frontend.local,traefik.default.protocol=https,traefik.backend=backend-server
      ## NOTE: Not all configuration is available - see the Backend: Docker documentation
      # Enables the docker configuration
      # - traefik.tags=api
      # - traefik.tags=car
      # - traefik.enable=true
      # - traefik.backend=backend.local
      # - traefik.docker.network=web
      # - traefik.frontend.rule=Host:frontend.local
      # - traefik.port=50051
      # - traefik.default.protocol=https
    networks:
      grpc:
        # Here, we give it a alias to the hostname
        aliases:
          - backend.local

  server1:
    image: alextanhongpin/grpc-server:latest
    ports:
      - 127.0.0.1::50052
    environment:
      - PORT=:50052
      - SSL_CERT=/run/secrets/backend.cert
      - SSL_KEY=/run/secrets/backend.key
    secrets:
      - backend.cert
      - backend.key
    networks:
      grpc:
        # Here, we give it a alias to the hostname
        aliases:
          - backend.local

  client:
    image: alextanhongpin/grpc-client:latest
    environment:
      - SSL_CERT=/run/secrets/frontend.cert
      - SRV_URL=frontend.local:4443
    secrets:
      - frontend.cert
    networks:
      grpc:

secrets:
  backend.cert: 
    file: ./cert/backend.cert
  backend.key: 
    file: ./cert/backend.key
  frontend.cert: 
    file: ./cert/frontend.cert
  frontend.key: 
    file: ./cert/frontend.key

networks:
  grpc: